### PR TITLE
Reworked plugin class to not use exception

### PR DESCRIPTION
**Pull request by eugene-manuilov**

### CODE REVIEW

**Comment by tott** [comment]
I'd second this addition. Currently with the way the Exception is thrown a failing gearman server will trigger a fatal error taking down a site.

**Review by dsawardekar — CHANGES_REQUESTED** [review]
@eugene-manuilov I am ok with switching to using WP_Error instead of Exceptions here. It would be good to have a few tests for the `build_client` and `build_worker` methods. We currently have few Mocks in PluginTest that become obsolete when we switch to WP_Error.

Also to @tott's note about fatal errors. We should also log an error_message if Client or Worker could not be built.

**Comment by jeffpaul** [comment]
@eugene-manuilov are you able to make the updates as noted by @dsawardekar's review?

**Comment by eugene-manuilov** [comment]
Hi @jeffpaul 

I have thought about these changes for a few days and I think we need to decline this PR because it introduces backward incompatible changes which can have a negative impact on all projects that use it and upgrade to the latest version without re-writing its integration. What are you thoughts?

**Comment by jeffpaul** [comment]
@tott @dsawardekar any major complaints from your end if we decline this PR?

**Comment by dsawardekar** [comment]
@jeffpaul No objections. We should try to maintain backwards compatibility in this plugin wherever possible.

**Pull request closed without merging**
